version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    # You can choose a random time here
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    time: '05:15'
    # The time zone should be either 'UTC' or a pretty name like
    # 'Asia/Tokyo'.
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
